name: Docs

on:
    push:
        branches:
            - '**'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build
              uses: andstor/jsdoc-action@v1
              with:
                  source_dir: ./capstone/src
                  output_dir: ./capstone/out
                  config_file: conf.json
                  template: better-docs
                  front_page: ./capstone/README.md

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: ./capstone/out
